apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: MONGO_DB_CONNECTION_STRING
              value: DELETED
            - name: MONGO_DB_NAME
              value: DELETED
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3000"
            - name: REDIS_URI
              value: DELETED
            - name: CORS_ORIGIN
              value: "*"
          image: us-central1-docker.pkg.dev/cloud-course-lab/app-repo/backend@sha256:3bb23ba0ec056fad699d1859a6108227491c5104fa027d321fb29da6ef2e63a6
          name: backend
          ports:
            - containerPort: 3000
            - containerPort: 14306
          resources: 
            requests:
              cpu: "350m"
      restartPolicy: Always
status: {}
