apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cloud-course-lab/app-repo/frontend@sha256:8d646155507a8c1a04296c5d1dc142c21e014101aff57ee728c51d7097396db9
          name: frontend
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "550m"
      restartPolicy: Always
status: {}
